version: '3'

# Taskfile principal - Tâches globales et inclusions
# Charge automatiquement les variables depuis le fichier .env s'il existe
dotenv: [ '.env' ]

includes:
  docker: ./docker/Taskfile.yml
  utils: ./utils/Taskfile.yml
  env: ./env/Taskfile.yml
  nodejs: ./nodejs/Taskfile.yml
  download: ./download/Taskfile.yml

vars:
  # Variables avec valeurs par défaut depuis .env ou valeurs de fallback
  PROJECT_NAME: '{{.PROJECT_NAME | default "taskfiles-collection"}}'
  PROJECT_VERSION: '1.0.0'
  ENVIRONMENT: '{{.ENVIRONMENT | default "development"}}'

tasks:
  default:
    desc: "Affiche l'aide et les tâches disponibles"
    silent: true
    cmds:
    - echo "🛠️  Collection de Taskfiles pour le développement"
    - echo ""
    - echo "Tâches globales disponibles :"
    - task --list
    - echo ""

  info:
    desc: "Affiche les informations du projet avec les variables d'environnement"
    silent: true
    cmds:
    - |
      echo "🛠️  {{.PROJECT_NAME}} v{{.PROJECT_VERSION}} - Collection de Taskfiles"
      echo "Environnement: {{.ENVIRONMENT}}"

  help:
    desc: "Affiche l'aide détaillée"
    silent: true
    aliases: [ h ]
    cmds:
    - task: default
