version: '3'

# Taskfile pour l'aide et la documentation
# Centralisé toutes les tâches d'aide des différents namespaces

tasks:
  default:
    desc: "Affiche l'aide générale"
    silent: true
    cmds:
    - echo "📚 Aide - Taskfiles Collection"
    - echo ""
    - echo "🎯 Namespaces disponibles :"
    - echo "  • docker   - Gestion Docker et conteneurs"
    - echo "  • env      - Variables d'environnement"
    - echo "  • nodejs   - Projets Node.js"
    - echo "  • download - Téléchargement d'outils"
    - echo "  • utils    - Utilitaires divers"
    - echo ""
    - echo "💡 Utilisez 'task help:<namespace>' pour l'aide détaillée"
    - echo "📖 Consultez USAGE.md pour la documentation complète"

  docker:
    desc: "Aide pour le namespace docker"
    silent: true
    summary: |
      Affiche l'aide détaillée pour toutes les tâches Docker disponibles.
      Couvre la gestion des conteneurs, images, stacks, swarm, monitoring, etc.
    cmds:
    - echo "🐳 Namespace Docker - Gestion des conteneurs et images"
    - echo ""
    - echo "📋 Catégories principales :"
    - echo "  • info      - Informations conteneurs/images"
    - echo "  • monitor   - Surveillance et diagnostics"
    - echo "  • stack     - Gestion des stacks Docker Swarm"
    - echo "  • swarm     - Gestion du cluster Swarm"
    - echo "  • network   - Gestion des réseaux"
    - echo "  • images    - Gestion des images"
    - echo "  • logs      - Gestion des logs conteneurs/services"
    - echo "  • analyze   - Analyse et historique"
    - echo ""
    - echo "📋 Sous-namespaces :"
    - echo "  • logs     - Gestion centralisée des logs"
    - echo "  • analyze  - Analyse et diagnostics avancés"
    - echo ""
    - echo "🔍 Tâches disponibles :"
    - task docker --list-all

  download:
    desc: "Aide pour le namespace download"
    silent: true
    summary: |
      Affiche l'aide pour le téléchargement d'outils de développement.
      Couvre les outils PHP et Python avec gestion automatisée.
    cmds:
    - echo "⬇️  Namespace Download - Téléchargement d'outils"
    - echo ""
    - echo "🎯 Langages disponibles :"
    - echo "  • PHP    - Collection d'outils de qualité et analyse"
    - echo "  • Python - Outils de développement et linting"
    - echo ""
    - echo "📋 Sous-namespaces :"
    - echo "  • php    - Gestion des outils PHP (.phar)"
    - echo "  • python - Gestion des outils Python (pip)"
    - echo ""
    - echo "🔧 Exemples d'utilisation :"
    - echo "  • task download:php:tools    - Télécharge tous les outils PHP"
    - echo "  • task download:php:list     - Liste les outils PHP"
    - echo "  • task download:python:tools - Installe tous les outils Python"
    - echo "  • task download:python:list  - Liste les outils Python"
    - echo ""
    - echo "🔗 Aliases de compatibilité :"
    - echo "  • task download:php-tools (utilise php:tools)"
    - echo "  • task download:python-tools (utilise python:tools)"
    - echo ""
    - echo "🔍 Tâches disponibles :"
    - task download --list-all
