version: '3'

# Taskfile pour l'aide et la documentation
# Centralisé toutes les tâches d'aide des différents namespaces

tasks:
  default:
    desc: "Affiche l'aide générale"
    silent: true
    cmds:
    - echo "📚 Aide - Taskfiles Collection"
    - echo ""
    - echo "🎯 Namespaces disponibles :"
    - echo "  • docker   - Gestion Docker et conteneurs"
    - echo "  • env      - Variables d'environnement"
    - echo "  • nodejs   - Projets Node.js"
    - echo "  • download - Téléchargement d'outils"
    - echo "  • utils    - Utilitaires divers"
    - echo ""
    - echo "💡 Utilisez 'task help:<namespace>' pour l'aide détaillée"
    - echo "📖 Consultez USAGE.md pour la documentation complète"

  docker:
    desc: "Aide pour le namespace docker"
    silent: true
    summary: |
      Affiche l'aide détaillée pour toutes les tâches Docker disponibles.
      Couvre la gestion des conteneurs, images, stacks, swarm, monitoring, etc.
    cmds:
    - echo "🐳 Namespace Docker - Gestion des conteneurs et images"
    - echo ""
    - echo "📋 Catégories principales :"
    - echo "  • info      - Informations conteneurs/images"
    - echo "  • monitor   - Surveillance et diagnostics"
    - echo "  • stack     - Gestion des stacks Docker Swarm"
    - echo "  • swarm     - Gestion du cluster Swarm"
    - echo "  • network   - Gestion des réseaux"
    - echo "  • images    - Gestion des images"
    - echo ""
    - echo "🔍 Tâches disponibles :"
    - task docker --list-all

  nodejs:
    desc: "Aide pour le namespace nodejs"
    silent: true
    summary: |
      Affiche l'aide pour la gestion des projets Node.js.
      Couvre l'installation de dépendances et la configuration.
    cmds:
    - echo "📦 Namespace Node.js - Gestion des projets Node.js"
    - echo ""
    - echo "🎯 Fonctionnalités principales :"
    - echo "  • Initialisation de projets"
    - echo "  • Installation de dépendances"
    - echo "  • Ajout automatique de devDependencies communes"
    - echo ""
    - echo "🔍 Tâches disponibles :"
    - task nodejs --list-all

  env:
    desc: "Aide pour le namespace env"
    silent: true
    summary: |
      Affiche l'aide pour la gestion des variables d'environnement.
      Couvre l'initialisation, validation et sauvegarde des fichiers .env.
    cmds:
    - echo "⚙️  Namespace ENV - Gestion des variables d'environnement"
    - echo ""
    - echo "🎯 Fonctionnalités principales :"
    - echo "  • Initialisation de fichiers .env"
    - echo "  • Validation de configuration"
    - echo "  • Affichage formaté du contenu"
    - echo "  • Sauvegarde et historique"
    - echo ""
    - echo "🔍 Tâches disponibles :"
    - task env --list-all

  download:
    desc: "Aide pour le namespace download"
    silent: true
    summary: |
      Affiche l'aide pour le téléchargement d'outils de développement.
      Couvre principalement les outils PHP mais extensible à d'autres langages.
    cmds:
    - echo "⬇️  Namespace Download - Téléchargement d'outils"
    - echo ""
    - echo "🎯 Outils disponibles :"
    - echo "  • PHP - Collection d'outils de qualité et analyse"
    - echo ""
    - echo "🔧 Outils PHP inclus :"
    - echo "  • phploc.phar (PHP Lines of Code)"
    - echo "  • php-cs-fixer.phar (PHP CS Fixer)"
    - echo "  • phpmd.phar (PHP Mess Detector)"
    - echo "  • phpcbf.phar (PHP Code Beautifier)"
    - echo "  • phpcs.phar (PHP Code Sniffer)"
    - echo "  • phpstan.phar (PHPStan)"
    - echo "  • phpDocumentor.phar"
    - echo "  • behat.phar (Behat)"
    - echo ""
    - echo "🔍 Tâches disponibles :"
    - task download --list-all

  utils:
    desc: "Aide pour le namespace utils"
    silent: true
    summary: |
      Affiche l'aide pour les utilitaires généraux.
      Couvre les sauvegardes, nettoyage, informations système, etc.
    cmds:
    - echo "🔧 Namespace Utils - Utilitaires divers"
    - echo ""
    - echo "🎯 Fonctionnalités principales :"
    - echo "  • Sauvegarde de projets"
    - echo "  • Nettoyage de fichiers temporaires"
    - echo "  • Informations système"
    - echo "  • Maintenance générale"
    - echo ""
    - echo "🔍 Tâches disponibles :"
    - task utils --list-all

  all:
    desc: "Affiche l'aide complète pour tous les namespaces"
    silent: true
    summary: |
      Affiche l'aide détaillée pour tous les namespaces disponibles.
      Utile pour avoir une vue d'ensemble complète du projet.
    cmds:
    - echo "📚 Aide complète - Tous les namespaces"
    - echo ""
    - task: help:docker
    - echo ""
    - echo "────────────────────────────────────────"
    - echo ""
    - task: help:nodejs
    - echo ""
    - echo "────────────────────────────────────────"
    - echo ""
    - task: help:env
    - echo ""
    - echo "────────────────────────────────────────"
    - echo ""
    - task: help:download
    - echo ""
    - echo "────────────────────────────────────────"
    - echo ""
    - task: help:utils

  quick:
    desc: "Guide de démarrage rapide"
    silent: true
    summary: |
      Affiche un guide de démarrage rapide avec les commandes essentielles.
    cmds:
    - |
      echo "🚀 Guide de démarrage rapide"
      echo ""
      echo "1️⃣  Initialisation :"
      echo "   task env:init         # Crée le fichier .env"
      echo "   task validate         # Valide la configuration"
      echo ""
      echo "2️⃣  Projets Node.js :"
      echo "   task nodejs:init      # Initialise le projet"
      echo "   task nodejs:add-dev-deps  # Ajoute les devDependencies"
      echo ""
      echo "3️⃣  Docker :"
      echo "   task docker:info:containers:running  # Liste les conteneurs"
      echo "   task docker:monitor:events           # Surveille les événements"
      echo ""
      echo "4️⃣  Outils PHP :"
      echo "   task download:php:tools     # Télécharge les outils"
      echo "   task download:php:tools:list # Liste les outils installés"
      echo ""
      echo "5️⃣  Utilitaires :"
      echo "   task utils:system:info      # Infos système"
      echo "   task utils:backup:create    # Sauvegarde du projet"
      echo ""
      echo "📖 Pour plus d'informations, utilisez task help:namespace"
