version: '3'

includes:
  swarm: ./swarm/Taskfile.yml
  images: ./images/Taskfile.yml
  info: ./info/Taskfile.yml
  monitor: ./monitor/Taskfile.yml
  network: ./network/Taskfile.yml
  stack: ./stack/Taskfile.yml
  logs: ./logs/Taskfile.yml
  analyze: ./analyze/Taskfile.yml

vars:
  CONTAINER_NAME: '{{.CONTAINER_NAME | default ""}}'
  IMAGE_NAME: '{{.IMAGE_NAME | default ""}}'

tasks:
  # Aliases pour compatibilité avec les anciennes commandes
  logs-container-tail:
    desc: "Affiche les logs d'un conteneur en temps réel (alias)"
    silent: true
    cmds:
    - task: logs:container:tail
      vars:
        CONTAINER_NAME: '{{.CONTAINER_NAME}}'
        LINES: '{{.LINES | default "100"}}'

  history-containers:
    desc: "Affiche l'historique des conteneurs (alias)"
    silent: true
    cmds:
    - task: analyze:history:containers
      vars:
        IMAGE_NAME: '{{.IMAGE_NAME}}'
        STATUS: '{{.STATUS}}'

  analyze-container-lifecycle:
    desc: "Analyse le cycle de vie d'un conteneur (alias)"
    silent: true
    cmds:
    - task: analyze:container:lifecycle
      vars:
        CONTAINER_NAME: '{{.CONTAINER_NAME}}'
