version: '3'

includes:
  swarm: ./swarm/Taskfile.yml
  images: ./images/Taskfile.yml
  info: ./info/Taskfile.yml
  monitor: ./monitor/Taskfile.yml
  network: ./network/Taskfile.yml
  stack: ./stack/Taskfile.yml
  logs: ./logs/Taskfile.yml
  analyze: ./analyze/Taskfile.yml

vars:
  CONTAINER_NAME: '{{.CONTAINER_NAME | default ""}}'
  IMAGE_NAME: '{{.IMAGE_NAME | default ""}}'

# Toutes les commandes sont maintenant organisées dans les sous-namespaces
# Utilisez les commandes via :
# - task logs:container:tail
# - task analyze:history:containers  
# - task analyze:container:lifecycle

# Pas de tâches directes dans ce namespace, utilisez les includes
