version: '3'

# Taskfile pour les utilitaires généraux

includes:
  backup: ./backup/Taskfile.yml
  clean: ./clean/Taskfile.yml
  system: ./system/Taskfile.yml

vars:
  BACKUP_DIR: '{{.BACKUP_DIR | default "./backups"}}'
  LOG_LEVEL: '{{.LOG_LEVEL | default "INFO"}}'

# Toutes les commandes sont maintenant organisées dans les sous-namespaces
# Utilisez les commandes via :
# - task backup:create, backup:list
# - task clean:logs
# - task system:info

# Pas de tâches directes dans ce namespace, utilisez les includes
