version: '3'

tasks:
  deploy:
    desc: "Déploie une stack Docker Swarm"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    vars:
      STACK_NAME: '{{.STACK_NAME | default "taskfiles-stack"}}'
      COMPOSE_FILE: '{{.COMPOSE_FILE | default "docker-compose.yml"}}'
    summary: |
      Déploie une stack Docker en utilisant docker stack deploy.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - COMPOSE_FILE: Fichier docker-compose à utiliser (défaut: docker-compose.yml)

      Exemples:
      task docker:stack:deploy
      task docker:stack:deploy STACK_NAME=mon-app
      task docker:stack:deploy STACK_NAME=mon-app COMPOSE_FILE=docker-stack.yml
    cmds:
    - |
      if [ ! -f "{{.COMPOSE_FILE}}" ]; then
        echo "❌ Le fichier '{{.COMPOSE_FILE}}' n'existe pas"
        echo "📁 Fichiers disponibles :"
        find . -name "docker-*.yml" -o -name "*compose*.yml" 2>/dev/null || echo "   Aucun fichier trouvé"
        exit 1
      fi

      echo "🚀 Déploiement de la stack '{{.STACK_NAME}}' avec le fichier '{{.COMPOSE_FILE}}'..."
      docker stack deploy -c {{.COMPOSE_FILE}} {{.STACK_NAME}}
      echo "✅ Stack '{{.STACK_NAME}}' déployée avec succès"

  deploy:with-build:
    desc: "Déploie une stack après avoir construit les images"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    vars:
      STACK_NAME: '{{.STACK_NAME | default "taskfiles-stack"}}'
      COMPOSE_FILE: '{{.COMPOSE_FILE | default "docker-compose.yml"}}'
    summary: |
      Construit les images puis déploie la stack Docker Swarm.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - COMPOSE_FILE: Fichier docker-compose (défaut: docker-compose.yml)
    cmds:
    - |
      if [ ! -f "{{.COMPOSE_FILE}}" ]; then
        echo "❌ Le fichier '{{.COMPOSE_FILE}}' n'existe pas"
        exit 1
      fi

      echo "🔨 Construction des images..."
      docker-compose -f {{.COMPOSE_FILE}} build

      echo "🚀 Déploiement de la stack '{{.STACK_NAME}}'..."
      docker stack deploy -c {{.COMPOSE_FILE}} {{.STACK_NAME}}
      echo "✅ Stack '{{.STACK_NAME}}' construite et déployée"

  update:
    desc: "Met à jour une stack existante"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    vars:
      STACK_NAME: '{{.STACK_NAME | default "taskfiles-stack"}}'
      COMPOSE_FILE: '{{.COMPOSE_FILE | default "docker-compose.yml"}}'
    summary: |
      Met à jour une stack Docker Swarm existante.
      Équivalent à docker stack deploy mais avec des messages spécifiques à la mise à jour.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - COMPOSE_FILE: Fichier docker-compose (défaut: docker-compose.yml)
    cmds:
    - |
      if ! docker stack ls --format "{{`{{.Name}}`}}" | grep -q "^{{.STACK_NAME}}$"; then
        echo "❌ La stack '{{.STACK_NAME}}' n'existe pas"
        echo "📋 Stacks disponibles :"
        docker stack ls
        exit 1
      fi

      echo "🔄 Mise à jour de la stack '{{.STACK_NAME}}'..."
      docker stack deploy -c {{.COMPOSE_FILE}} {{.STACK_NAME}}
      echo "✅ Stack '{{.STACK_NAME}}' mise à jour"

  remove:
    desc: "Supprime une stack Docker Swarm"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    vars:
      STACK_NAME: '{{.STACK_NAME | default "taskfiles-stack"}}'
    summary: |
      Supprime complètement une stack Docker Swarm.

      Variables:
      - STACK_NAME: Nom de la stack à supprimer (défaut: taskfiles-stack)
    cmds:
    - |
      if ! docker stack ls --format "{{`{{.Name}}`}}" | grep -q "^{{.STACK_NAME}}$"; then
        echo "❌ La stack '{{.STACK_NAME}}' n'existe pas"
        echo "📋 Stacks disponibles :"
        docker stack ls
        exit 1
      fi

      echo "🗑️  Suppression de la stack '{{.STACK_NAME}}'..."
      docker stack rm {{.STACK_NAME}}
      echo "✅ Stack '{{.STACK_NAME}}' supprimée"

  list:
    desc: "Liste toutes les stacks Docker Swarm"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: "Affiche la liste de toutes les stacks déployées"
    cmds:
    - echo "📋 Stacks Docker Swarm déployées :"
    - docker stack ls

  services:
    desc: "Liste les services d'une stack"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    vars:
      STACK_NAME: '{{.STACK_NAME | default "taskfiles-stack"}}'
    summary: |
      Affiche tous les services d'une stack spécifique.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
    cmds:
    - |
      if ! docker stack ls --format "{{`{{.Name}}`}}" | grep -q "^{{.STACK_NAME}}$"; then
        echo "❌ La stack '{{.STACK_NAME}}' n'existe pas"
        echo "📋 Stacks disponibles :"
        docker stack ls
        exit 1
      fi

      echo "🔧 Services de la stack '{{.STACK_NAME}}' :"
      docker stack services {{.STACK_NAME}}

  ps:
    desc: "Affiche les tâches/conteneurs d'une stack"
    silent: true
    vars:
      STACK_NAME: '{{.STACK_NAME | default "taskfiles-stack"}}'
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Affiche toutes les tâches (conteneurs) d'une stack.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
    cmds:
    - |
      if ! docker stack ls --format "{{`{{.Name}}`}}" | grep -q "^{{.STACK_NAME}}$"; then
        echo "❌ La stack '{{.STACK_NAME}}' n'existe pas"
        echo "📋 Stacks disponibles :"
        docker stack ls
        exit 1
      fi

      echo "📦 Tâches de la stack '{{.STACK_NAME}}' :"
      docker stack ps {{.STACK_NAME}}

  logs:
    desc: "Affiche les logs d'un service de la stack"
    silent: true
    vars:
      STACK_NAME: '{{.STACK_NAME | default "taskfiles-stack"}}'
      SERVICE_NAME: '{{.SERVICE_NAME | default ""}}'
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Affiche les logs d'un service spécifique dans une stack.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - SERVICE_NAME: Nom du service (requis)

      Exemple:
      task docker:stack:logs STACK_NAME=mon-app SERVICE_NAME=web
    cmds:
    - |
      if [ -z "{{.SERVICE_NAME}}" ]; then
        echo "❌ SERVICE_NAME est requis"
        echo "🔧 Services disponibles pour la stack '{{.STACK_NAME}}' :"
        docker stack services {{.STACK_NAME}} --format "table {{.Name}}\t{{.Replicas}}\t{{.Image}}"
        exit 1
      fi

      echo "📄 Logs du service '{{.STACK_NAME}}_{{.SERVICE_NAME}}' :"
      docker service logs {{.STACK_NAME}}_{{.SERVICE_NAME}} --follow

  validate:
    desc: "Valide un fichier docker-compose pour Docker Swarm"
    silent: true
    vars:
      COMPOSE_FILE: '{{.COMPOSE_FILE | default "docker-compose.yml"}}'
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Valide la syntaxe d'un fichier docker-compose avant déploiement.

      Variables:
      - COMPOSE_FILE: Fichier à valider (défaut: docker-compose.yml)
    cmds:
    - |
      if [ ! -f "{{.COMPOSE_FILE}}" ]; then
        echo "❌ Le fichier '{{.COMPOSE_FILE}}' n'existe pas"
        exit 1
      fi

      echo "✅ Validation du fichier '{{.COMPOSE_FILE}}'..."
      docker-compose -f {{.COMPOSE_FILE}} config
      echo "✅ Fichier valide"

  check:containers:ready:
    desc: "Vérifie que les conteneurs spécifiés sont prêts"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Vérifie que les conteneurs d'une liste sont tous actifs et en bonne santé.
      Attend et vérifie périodiquement jusqu'à ce que tous soient prêts ou timeout.

      Variables:
      - CONTAINERS: Liste des conteneurs séparés par des virgules (ex: "traefik,portainer")
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - TIMEOUT: Timeout en secondes (défaut: 300)
      - CHECK_INTERVAL: Intervalle entre les vérifications en secondes (défaut: 10)

      Exemple:
      task docker:stack:check:containers:ready CONTAINERS="traefik,portainer" STACK_NAME=mon-app
    vars:
      TIMEOUT: '{{.TIMEOUT | default "300"}}'
      CHECK_INTERVAL: '{{.CHECK_INTERVAL | default "10"}}'
      STACK_NAME: '{{.STACK_NAME | default "taskfiles-stack"}}'
      CONTAINERS: '{{.CONTAINERS | default ""}}'
    cmds:
    - |
      if [ -z "{{.CONTAINERS}}" ]; then
        echo "❌ CONTAINERS est requis (ex: 'traefik,portainer')"
        exit 1
      fi

      echo "🔍 Vérification de l'état des conteneurs : {{.CONTAINERS}}"
      echo "🕐 Timeout: {{.TIMEOUT}}s, Intervalle de vérification: {{.CHECK_INTERVAL}}s"
      echo ""

      start_time=$(date +%s)
      timeout_time=$((start_time + {{.TIMEOUT}}))

      # Convertir la liste en tableau compatible POSIX
      containers_list="{{.CONTAINERS}}"
      containers_clean=$(echo "$containers_list" | tr ',' ' ')

      # Compteur de vérifications
      check_count=0

      while true; do
        current_time=$(date +%s)
        check_count=$((check_count + 1))
        
        # Vérifier le timeout
        if [ $current_time -gt $timeout_time ]; then
          echo ""
          echo "❌ Timeout atteint ({{.TIMEOUT}}s). Tous les conteneurs ne sont pas encore prêts."
          echo "📋 État final des conteneurs :"
          docker ps --filter "name={{.STACK_NAME}}" --format "table {{.Names}}\t{{.Status}}"
          exit 1
        fi
        
        all_ready=true
        ready_containers=""
        missing_containers=""
        
        # Vérifier chaque conteneur
        for container in $containers_clean; do
          container=$(echo "$container" | xargs)  # Trim whitespace
          
          if docker ps --filter "name={{.STACK_NAME}}_${container}" --format "{{.Names}}" | grep -q "{{.STACK_NAME}}_${container}"; then
            ready_containers="$ready_containers $container"
          else
            missing_containers="$missing_containers $container"
            all_ready=false
          fi
        done
        
        # Affichage de l'état
        elapsed=$((current_time - start_time))
        echo "⏳ Vérification #$check_count (${elapsed}s/{{.TIMEOUT}}s)"
        
        if [ -n "$ready_containers" ]; then
          echo "  ✅ Prêts     :$ready_containers"
        fi
        
        if [ -n "$missing_containers" ]; then
          echo "  ⏳ En attente :$missing_containers"
        fi
        
        # Si tous les conteneurs sont prêts, on sort de la boucle
        if [ "$all_ready" = true ]; then
          echo ""
          echo "🎉 Succès ! Tous les conteneurs sont actifs !"
          echo "⏱️  Temps total d'attente : ${elapsed}s"
          echo ""
          echo "📋 Conteneurs actifs :"
          for container in $containers_clean; do
            container=$(echo "$container" | xargs)
            status=$(docker ps --filter "name={{.STACK_NAME}}_${container}" --format "{{.Status}}")
            echo "  ✅ ${container} - $status"
          done
          break
        fi
        
        echo ""
        sleep {{.CHECK_INTERVAL}}
      done

  wait:containers:ready:
    desc: "Attend que les conteneurs spécifiés soient prêts"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Attend que tous les conteneurs d'une liste soient actifs et en bonne santé.
      Effectue des vérifications périodiques jusqu'au timeout.

      Variables:
      - CONTAINERS: Liste des conteneurs séparés par des virgules (ex: "traefik,portainer")
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - TIMEOUT: Timeout en secondes (défaut: 300)
      - CHECK_INTERVAL: Intervalle entre les vérifications en secondes (défaut: 10)

      Exemple:
      task docker:stack:wait:containers:ready CONTAINERS="traefik,portainer" TIMEOUT=600
    vars:
      TIMEOUT: '{{.TIMEOUT | default "300"}}'
      CHECK_INTERVAL: '{{.CHECK_INTERVAL | default "10"}}'
      STACK_NAME: '{{.STACK_NAME | default "taskfiles-stack"}}'
      CONTAINERS: '{{.CONTAINERS | default ""}}'
    cmds:
    - |
      if [ -z "{{.CONTAINERS}}" ]; then
        echo "❌ CONTAINERS est requis (ex: 'traefik,portainer')"
        exit 1
      fi

      echo "⏳ Attente que les conteneurs soient prêts : {{.CONTAINERS}}"
      echo "🕐 Timeout: {{.TIMEOUT}}s, Intervalle de vérification: {{.CHECK_INTERVAL}}s"

      start_time=$(date +%s)
      timeout_time=$((start_time + {{.TIMEOUT}}))

      # Convertir la liste en format compatible POSIX
      containers_list="{{.CONTAINERS}}"
      containers_clean=$(echo "$containers_list" | tr ',' ' ')

      while true; do
        current_time=$(date +%s)
        
        if [ $current_time -gt $timeout_time ]; then
          echo "❌ Timeout atteint ({{.TIMEOUT}}s). Les conteneurs ne sont pas tous prêts."
          exit 1
        fi
        
        all_ready=true
        
        for container in $containers_clean; do
          container=$(echo "$container" | xargs)  # Trim whitespace
          
          if ! docker ps --filter "name={{.STACK_NAME}}_${container}" --format "{{.Names}}" | grep -q "{{.STACK_NAME}}_${container}"; then
            all_ready=false
            break
          fi
        done
        
        if [ "$all_ready" = true ]; then
          echo "✅ Tous les conteneurs sont prêts!"
          break
        fi
        
        elapsed=$((current_time - start_time))
        echo "⏳ Attente... (${elapsed}s/{{.TIMEOUT}}s)"
        sleep {{.CHECK_INTERVAL}}
      done
