version: '3'

vars:
  STACK_NAME: '{{.STACK_NAME | default "taskfiles-stack"}}'
  COMPOSE_FILE: '{{.COMPOSE_FILE | default "docker-compose.yml"}}'
  SWARM_COMPOSE_FILE: '{{.SWARM_COMPOSE_FILE | default "docker-stack.yml"}}'

tasks:
  deploy:
    desc: "Déploie une stack Docker Swarm"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Déploie une stack Docker en utilisant docker stack deploy.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - COMPOSE_FILE: Fichier docker-compose à utiliser (défaut: docker-compose.yml)

      Exemples:
      task docker:stack:deploy
      task docker:stack:deploy STACK_NAME=mon-app
      task docker:stack:deploy STACK_NAME=mon-app COMPOSE_FILE=docker-stack.yml
    cmds:
    - |
      if [ ! -f "{{.COMPOSE_FILE}}" ]; then
        echo "❌ Le fichier '{{.COMPOSE_FILE}}' n'existe pas"
        echo "📁 Fichiers disponibles :"
        find . -name "docker-*.yml" -o -name "*compose*.yml" 2>/dev/null || echo "   Aucun fichier trouvé"
        exit 1
      fi

      echo "🚀 Déploiement de la stack '{{.STACK_NAME}}' avec le fichier '{{.COMPOSE_FILE}}'..."
      docker stack deploy -c {{.COMPOSE_FILE}} {{.STACK_NAME}}
      echo "✅ Stack '{{.STACK_NAME}}' déployée avec succès"

  deploy:with-build:
    desc: "Déploie une stack après avoir construit les images"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Construit les images puis déploie la stack Docker Swarm.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - COMPOSE_FILE: Fichier docker-compose (défaut: docker-compose.yml)
    cmds:
    - |
      if [ ! -f "{{.COMPOSE_FILE}}" ]; then
        echo "❌ Le fichier '{{.COMPOSE_FILE}}' n'existe pas"
        exit 1
      fi

      echo "🔨 Construction des images..."
      docker-compose -f {{.COMPOSE_FILE}} build

      echo "🚀 Déploiement de la stack '{{.STACK_NAME}}'..."
      docker stack deploy -c {{.COMPOSE_FILE}} {{.STACK_NAME}}
      echo "✅ Stack '{{.STACK_NAME}}' construite et déployée"

  update:
    desc: "Met à jour une stack existante"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Met à jour une stack Docker Swarm existante.
      Équivalent à docker stack deploy mais avec des messages spécifiques à la mise à jour.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - COMPOSE_FILE: Fichier docker-compose (défaut: docker-compose.yml)
    cmds:
    - |
      if ! docker stack ls --format "{{.Name}}" | grep -q "^{{.STACK_NAME}}$"; then
        echo "❌ La stack '{{.STACK_NAME}}' n'existe pas"
        echo "📋 Stacks disponibles :"
        docker stack ls
        exit 1
      fi

      echo "🔄 Mise à jour de la stack '{{.STACK_NAME}}'..."
      docker stack deploy -c {{.COMPOSE_FILE}} {{.STACK_NAME}}
      echo "✅ Stack '{{.STACK_NAME}}' mise à jour"

  remove:
    desc: "Supprime une stack Docker Swarm"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Supprime complètement une stack Docker Swarm.

      Variables:
      - STACK_NAME: Nom de la stack à supprimer (défaut: taskfiles-stack)
    cmds:
    - |
      if ! docker stack ls --format "{{.Name}}" | grep -q "^{{.STACK_NAME}}$"; then
        echo "❌ La stack '{{.STACK_NAME}}' n'existe pas"
        echo "📋 Stacks disponibles :"
        docker stack ls
        exit 1
      fi

      echo "🗑️  Suppression de la stack '{{.STACK_NAME}}'..."
      docker stack rm {{.STACK_NAME}}
      echo "✅ Stack '{{.STACK_NAME}}' supprimée"

  list:
    desc: "Liste toutes les stacks Docker Swarm"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: "Affiche la liste de toutes les stacks déployées"
    cmds:
    - echo "📋 Stacks Docker Swarm déployées :"
    - docker stack ls

  services:
    desc: "Liste les services d'une stack"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Affiche tous les services d'une stack spécifique.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
    cmds:
    - |
      if ! docker stack ls --format "{{.Name}}" | grep -q "^{{.STACK_NAME}}$"; then
        echo "❌ La stack '{{.STACK_NAME}}' n'existe pas"
        echo "📋 Stacks disponibles :"
        docker stack ls
        exit 1
      fi

      echo "🔧 Services de la stack '{{.STACK_NAME}}' :"
      docker stack services {{.STACK_NAME}}

  ps:
    desc: "Affiche les tâches/conteneurs d'une stack"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Affiche toutes les tâches (conteneurs) d'une stack.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
    cmds:
    - |
      if ! docker stack ls --format "{{.Name}}" | grep -q "^{{.STACK_NAME}}$"; then
        echo "❌ La stack '{{.STACK_NAME}}' n'existe pas"
        echo "📋 Stacks disponibles :"
        docker stack ls
        exit 1
      fi

      echo "📦 Tâches de la stack '{{.STACK_NAME}}' :"
      docker stack ps {{.STACK_NAME}}

  logs:
    desc: "Affiche les logs d'un service de la stack"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Affiche les logs d'un service spécifique dans une stack.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - SERVICE_NAME: Nom du service (requis)

      Exemple:
      task docker:stack:logs STACK_NAME=mon-app SERVICE_NAME=web
    cmds:
    - |
      if [ -z "{{.SERVICE_NAME}}" ]; then
        echo "❌ SERVICE_NAME est requis"
        echo "🔧 Services disponibles pour la stack '{{.STACK_NAME}}' :"
        docker stack services {{.STACK_NAME}} --format "table {{.Name}}\t{{.Replicas}}\t{{.Image}}"
        exit 1
      fi

      echo "📄 Logs du service '{{.STACK_NAME}}_{{.SERVICE_NAME}}' :"
      docker service logs {{.STACK_NAME}}_{{.SERVICE_NAME}} --follow

  validate:
    desc: "Valide un fichier docker-compose pour Docker Swarm"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Valide la syntaxe d'un fichier docker-compose avant déploiement.

      Variables:
      - COMPOSE_FILE: Fichier à valider (défaut: docker-compose.yml)
    cmds:
    - |
      if [ ! -f "{{.COMPOSE_FILE}}" ]; then
        echo "❌ Le fichier '{{.COMPOSE_FILE}}' n'existe pas"
        exit 1
      fi

      echo "✅ Validation du fichier '{{.COMPOSE_FILE}}'..."
      docker-compose -f {{.COMPOSE_FILE}} config
      echo "✅ Fichier valide"

  check:containers:ready:
    desc: "Vérifie que les conteneurs spécifiés sont prêts"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Vérifie que les conteneurs d'une liste sont tous actifs et en bonne santé.

      Variables:
      - CONTAINERS: Liste des conteneurs séparés par des virgules (ex: "traefik,portainer")
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - TIMEOUT: Timeout en secondes (défaut: 300)

      Exemple:
      task docker:stack:check:containers:ready CONTAINERS="traefik,portainer" STACK_NAME=mon-app
    vars:
      TIMEOUT: '{{.TIMEOUT | default "300"}}'
    cmds:
    - |
      if [ -z "{{.CONTAINERS}}" ]; then
        echo "❌ CONTAINERS est requis (ex: 'traefik,portainer')"
        exit 1
      fi

      echo "🔍 Vérification de l'état des conteneurs : {{.CONTAINERS}}"

      # Convertir la liste en tableau compatible POSIX
      containers_list="{{.CONTAINERS}}"

      # Remplacer les virgules par des espaces et traiter chaque conteneur
      containers_clean=$(echo "$containers_list" | tr ',' ' ')

      for container in $containers_clean; do
        container=$(echo "$container" | xargs)  # Trim whitespace
        echo "📦 Vérification du conteneur: $container"
        
        # Vérifier si le conteneur existe et est en cours d'exécution
        if docker ps --filter "name={{.STACK_NAME}}_${container}" --format "{{.Names}}" | grep -q "{{.STACK_NAME}}_${container}"; then
          echo "✅ Conteneur $container est actif"
        else
          echo "❌ Conteneur $container n'est pas actif ou n'existe pas"
          echo "📋 Conteneurs disponibles pour la stack {{.STACK_NAME}} :"
          docker ps --filter "name={{.STACK_NAME}}" --format "table {{.Names}}\t{{.Status}}"
          exit 1
        fi
      done

      echo "✅ Tous les conteneurs sont actifs!"

  wait:containers:ready:
    desc: "Attend que les conteneurs spécifiés soient prêts"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Attend que tous les conteneurs d'une liste soient actifs et en bonne santé.
      Effectue des vérifications périodiques jusqu'au timeout.

      Variables:
      - CONTAINERS: Liste des conteneurs séparés par des virgules (ex: "traefik,portainer")
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - TIMEOUT: Timeout en secondes (défaut: 300)
      - CHECK_INTERVAL: Intervalle entre les vérifications en secondes (défaut: 10)

      Exemple:
      task docker:stack:wait:containers:ready CONTAINERS="traefik,portainer" TIMEOUT=600
    vars:
      TIMEOUT: '{{.TIMEOUT | default "300"}}'
      CHECK_INTERVAL: '{{.CHECK_INTERVAL | default "10"}}'
    cmds:
    - |
      if [ -z "{{.CONTAINERS}}" ]; then
        echo "❌ CONTAINERS est requis (ex: 'traefik,portainer')"
        exit 1
      fi

      echo "⏳ Attente que les conteneurs soient prêts : {{.CONTAINERS}}"
      echo "🕐 Timeout: {{.TIMEOUT}}s, Intervalle de vérification: {{.CHECK_INTERVAL}}s"

      start_time=$(date +%s)
      timeout_time=$((start_time + {{.TIMEOUT}}))

      # Convertir la liste en format compatible POSIX
      containers_list="{{.CONTAINERS}}"
      containers_clean=$(echo "$containers_list" | tr ',' ' ')

      while true; do
        current_time=$(date +%s)
        
        if [ $current_time -gt $timeout_time ]; then
          echo "❌ Timeout atteint ({{.TIMEOUT}}s). Les conteneurs ne sont pas tous prêts."
          exit 1
        fi
        
        all_ready=true
        
        for container in $containers_clean; do
          container=$(echo "$container" | xargs)  # Trim whitespace
          
          if ! docker ps --filter "name={{.STACK_NAME}}_${container}" --format "{{.Names}}" | grep -q "{{.STACK_NAME}}_${container}"; then
            all_ready=false
            break
          fi
        done
        
        if [ "$all_ready" = true ]; then
          echo "✅ Tous les conteneurs sont prêts!"
          break
        fi
        
        elapsed=$((current_time - start_time))
        echo "⏳ Attente... (${elapsed}s/{{.TIMEOUT}}s)"
        sleep {{.CHECK_INTERVAL}}
      done

  check:containers:health:
    desc: "Vérifie la santé des conteneurs avec healthcheck"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Vérifie l'état de santé des conteneurs qui ont un healthcheck configuré.

      Variables:
      - CONTAINERS: Liste des conteneurs séparés par des virgules (ex: "traefik,portainer")
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
    cmds:
    - |
      if [ -z "{{.CONTAINERS}}" ]; then
        echo "❌ CONTAINERS est requis (ex: 'traefik,portainer')"
        exit 1
      fi

      echo "🏥 Vérification de la santé des conteneurs : {{.CONTAINERS}}"

      # Convertir la liste en tableau
      IFS=',' read -ra CONTAINER_ARRAY <<< "{{.CONTAINERS}}"

      for container in "${CONTAINER_ARRAY[@]}"; do
        container=$(echo "$container" | xargs)  # Trim whitespace
        full_name="{{.STACK_NAME}}_${container}"
        
        echo "🔍 Vérification de $container..."
        
        # Vérifier si le conteneur existe
        if ! docker ps --filter "name=$full_name" --format "{{.Names}}" | grep -q "$full_name"; then
          echo "❌ Conteneur $container n'existe pas ou n'est pas actif"
          continue
        fi
        
        # Obtenir l'état de santé
        health_status=$(docker inspect $full_name --format='{{.State.Health.Status}}' 2>/dev/null || echo "no-healthcheck")
        
        case $health_status in
          "healthy")
            echo "✅ $container: Sain"
            ;;
          "unhealthy")
            echo "❌ $container: Non sain"
            ;;
          "starting")
            echo "🟡 $container: Démarrage en cours"
            ;;
          "no-healthcheck")
            echo "ℹ️  $container: Pas de healthcheck configuré"
            ;;
          *)
            echo "❓ $container: État inconnu ($health_status)"
            ;;
        esac
      done

  deploy:with:wait:
    desc: "Déploie une stack et attend que les conteneurs soient prêts"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Déploie une stack et attend que les conteneurs spécifiés soient actifs.

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - COMPOSE_FILE: Fichier docker-compose (défaut: docker-compose.yml)
      - CONTAINERS: Liste des conteneurs à vérifier (ex: "traefik,portainer")
      - TIMEOUT: Timeout en secondes (défaut: 300)

      Exemple:
      task docker:stack:deploy:with:wait CONTAINERS="traefik,portainer" TIMEOUT=600
    cmds:
    - task: deploy
    - |
      if [ -n "{{.CONTAINERS}}" ]; then
        task docker:stack:wait:containers:ready CONTAINERS="{{.CONTAINERS}}" STACK_NAME="{{.STACK_NAME}}" TIMEOUT="{{.TIMEOUT | default \"300\"}}"
      else
        echo "ℹ️  Aucun conteneur spécifique à vérifier (CONTAINERS non défini)"
        echo "⏳ Attente de 30 secondes pour la stabilisation..."
        sleep 30
      fi

  full-deploy:
    desc: "Déploiement complet : validation + construction + déploiement"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Effectue un déploiement complet avec toutes les étapes :
      1. Validation du fichier docker-compose
      2. Construction des images si nécessaire
      3. Déploiement de la stack
      4. Vérification du statut

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - COMPOSE_FILE: Fichier docker-compose (défaut: docker-compose.yml)
    cmds:
    - task: docker:stack:validate
    - |
      echo "🔨 Construction des images..."
      docker-compose -f {{.COMPOSE_FILE}} build
    - task: stack:deploy
    - |
      echo "⏳ Attente du déploiement..."
      sleep 5
    - task: docker:stack:services
    - task: docker:stack:ps

  full-deploy:with:wait:
    desc: "Déploiement complet avec attente des conteneurs"
    silent: true
    preconditions:
    - sh: command -v docker
      msg: "Docker n'est pas installé ou accessible"
    summary: |
      Effectue un déploiement complet et attend que les conteneurs soient prêts :
      1. Validation du fichier docker-compose
      2. Construction des images si nécessaire
      3. Déploiement de la stack
      4. Attente que les conteneurs soient actifs
      5. Vérification du statut

      Variables:
      - STACK_NAME: Nom de la stack (défaut: taskfiles-stack)
      - COMPOSE_FILE: Fichier docker-compose (défaut: docker-compose.yml)
      - CONTAINERS: Liste des conteneurs à vérifier (ex: "traefik,portainer")
      - TIMEOUT: Timeout en secondes (défaut: 300)
    cmds:
    - task: docker:stack:validate
    - |
      echo "🔨 Construction des images..."
      docker-compose -f {{.COMPOSE_FILE}} build
    - task: deploy:with:wait
    - task: docker:stack:services
    - task: docker:stack:ps
