version: '3'

tasks:
  init:
    desc: "Initialise le fichier .env depuis .env.example"
    silent: true
    cmds:
    - |
      if [ ! -f ".env" ]; then
        if [ -f ".env.example" ]; then
          cp .env.example .env
          echo "✅ Fichier .env créé depuis .env.example"
          echo "📝 Veuillez éditer le fichier .env pour ajuster les valeurs"
        else
          echo "❌ Fichier .env.example non trouvé"
          exit 1
        fi
      else
        echo "ℹ️  Le fichier .env existe déjà"
      fi

  validate:
    desc: "Valide la configuration du fichier .env"
    silent: true
    cmds:
    - |
      if [ ! -f ".env" ]; then
        echo "❌ Fichier .env non trouvé. Exécutez 'task env-init' d'abord."
        exit 1
      fi
    - echo "✅ Fichier .env trouvé"
    - |
      # Vérification des variables critiques
      missing_vars=""
      if [ -z "{{.PROJECT_NAME}}" ]; then missing_vars="$missing_vars PROJECT_NAME"; fi
      if [ -z "{{.PROJECT_VERSION}}" ]; then missing_vars="$missing_vars PROJECT_VERSION"; fi
      if [ -z "{{.ENVIRONMENT}}" ]; then missing_vars="$missing_vars ENVIRONMENT"; fi

      if [ -n "$missing_vars" ]; then
        echo "❌ Variables manquantes dans .env: $missing_vars"
        exit 1
      else
        echo "✅ Configuration .env valide"
      fi
