name: CI Pipeline
on: 
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    env:
      DOCKER_INTERACTIVE: false
    steps:
      # === SETUP PHASE ===
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1
      
      - name: Setup Task
        uses: go-task/setup-task@v1
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
            if [ ! -d node_modules ]; then
                npm install
            fi
      
      - name: Setup environment files
        run: |
          cp .env.example .env
      
      - name: lint all
        run: task lint:all